services:
  admin-cdp:
    build: .
    ports:
      - "8519:8501"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - webapp_cdp_static_net

networks:
  webapp_cdp_static_net:
    name: webapp_cdp_static_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.240.0/24
