services:
  admin-cdp:
    build: .
    ports:
      - "8519:8501"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - admin_cdp_net

networks:
  admin_cdp_net:
    name: admin_cdp_net
    driver: bridge
