services:
  admin-cdp:
    build: .
    ports:
      - "8519:8501"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - webapp_cdp_static_net

networks:
  webapp_cdp_static_net:
    external: true
    name: webapp_cdp_static_net
